### ISSUE TITLE
Improve docker-compose for using latest template

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-rocketchat#1]

**Comment by qiaofeng1227** [comment]
Done

**Comment by qiaofeng1227** [comment]
replace the url 
![image](https://user-images.githubusercontent.com/43192516/118578116-31141100-b7be-11eb-927e-898a839be3c2.png)

**Comment by qiaofeng1227** [comment]
```
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                                       NAMES
e3cb47782861   rocketchat/hubot-rocketchat:latest   "/bin/sh -c 'node -e…"   18 seconds ago   Up 16 seconds   0.0.0.0:3001->8080/tcp, :::3001->8080/tcp   docker-rocketchat_hubot_1
80fdc6314278   rocketchat/rocket.chat:latest        "docker-entrypoint.s…"   18 seconds ago   Up 17 seconds   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   docker-rocketchat_rocketchat_1
13d49818f6fc   mongo:4.0                            "docker-entrypoint.s…"   19 seconds ago   Up 18 seconds   27017/tcp                                   docker-rocketchat_mongo_1
```

**Comment by qiaofeng1227** [comment]
![Uploading image.png…]()

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/118622414-e2846800-b7f9-11eb-97f2-971707cfe094.png)

**Comment by qiaofeng1227** [comment]
docker logs rocketchat
```
Using GridFS for custom emoji storage
➔ System ➔ startup
➔ +----------------------------------------------+
➔ |                SERVER RUNNING                |
➔ +----------------------------------------------+
➔ |                                              |
➔ |  Rocket.Chat Version: 3.14.0                 |
➔ |       NodeJS Version: 12.22.1 - x64          |
➔ |      MongoDB Version: 4.0.24                 |
➔ |       MongoDB Engine: mmapv1                 |
➔ |             Platform: linux                  |
➔ |         Process Port: 3000                   |
➔ |             Site URL: http://127.0.0.1:9001  |
➔ |     ReplicaSet OpLog: Enabled                |
➔ |          Commit Hash: 1255c8f0ca             |
➔ |        Commit Branch: HEAD                   |
➔ |                                              |
➔ +----------------------------------------------+
(node:10) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Exception while invoking method registerUser Error: Email already exists. [403]
    at handleError (packages/accounts-password/password_server.js:110:17)
    at checkForCaseInsensitiveDuplicates (packages/accounts-password/password_server.js:257:7)
    at createUser (packages/accounts-password/password_server.js:1130:3)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1218:10)
    at MethodInvocation.registerUser (server/methods/registerUser.js:72:22)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:263:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
```

**Comment by qiaofeng1227** [comment]
```
2021-05-18T08:57:46.335+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:46.336+0000 I INDEX    [conn2] build index on: rocketchat.rocketchat_apps_logs properties: { v: 2, key: { appId: 1 }, name: "appId_1", ns: "rocketchat.rocketchat_apps_logs" }
2021-05-18T08:57:46.336+0000 I INDEX    [conn2] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:46.336+0000 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:46.337+0000 I SHARDING [conn7] Marking collection rocketchat.rocketchat_apps_persistence as collection version: <unsharded>
2021-05-18T08:57:46.338+0000 I STORAGE  [conn8] createCollection: rocketchat.rocketchat_apps_persistence with generated UUID: 96b5ed55-2115-46fb-8962-ff10f3ab5ee1
2021-05-18T08:57:46.339+0000 I INDEX    [conn8] build index on: rocketchat.rocketchat_apps_persistence properties: { v: 2, key: { _updatedAt: 1 }, name: "_updatedAt_1", ns: "rocketchat.rocketchat_apps_persistence" }
2021-05-18T08:57:46.339+0000 I INDEX    [conn8] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:46.339+0000 I INDEX    [conn8] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:46.355+0000 I STORAGE  [conn3] createCollection: rocketchat.rocketchat_apps_scheduler with generated UUID: 852108e5-a62d-4763-a0a6-602656225815
2021-05-18T08:57:46.357+0000 I INDEX    [conn3] build index on: rocketchat.rocketchat_apps_scheduler properties: { v: 2, key: { name: 1, nextRunAt: 1, priority: -1, lockedAt: 1, disabled: 1 }, name: "findAndLockNextJobIndex", ns: "rocketchat.rocketchat_apps_scheduler" }
2021-05-18T08:57:46.357+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:46.357+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:46.363+0000 I COMMAND  [conn3] CMD: drop rocketchat.rocketchat_raw_imports
2021-05-18T08:57:46.363+0000 I STORAGE  [conn3] dropCollection: rocketchat.rocketchat_raw_imports (8e7e3ed8-6f4a-4063-88a5-9fdbcbc70b77) - renaming to drop-pending collection: rocketchat.system.drop.1621328266i82t1.rocketchat_raw_imports with drop optime { ts: Timestamp(1621328266, 82), t: 1 }
2021-05-18T08:57:46.363+0000 I STORAGE  [conn3] renameCollection: renaming collection 8e7e3ed8-6f4a-4063-88a5-9fdbcbc70b77 from rocketchat.rocketchat_raw_imports to rocketchat.system.drop.1621328266i82t1.rocketchat_raw_imports
2021-05-18T08:57:46.438+0000 I REPL     [replication-0] Completing collection drop for rocketchat.system.drop.1621328266i82t1.rocketchat_raw_imports with drop optime { ts: Timestamp(1621328266, 82), t: 1 } (notification optime: { ts: Timestamp(1621328266, 97), t: 1 })
2021-05-18T08:57:46.438+0000 I STORAGE  [replication-0] Finishing collection drop for rocketchat.system.drop.1621328266i82t1.rocketchat_raw_imports (8e7e3ed8-6f4a-4063-88a5-9fdbcbc70b77).
2021-05-18T08:57:47.966+0000 I INDEX    [conn3] build index on: rocketchat.rocketchat_message properties: { v: 2, key: { pinnedBy._id: 1 }, name: "pinnedBy._id_1", ns: "rocketchat.rocketchat_message", sparse: 1 }
2021-05-18T08:57:47.966+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:47.966+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:47.998+0000 I INDEX    [conn3] build index on: rocketchat.rocketchat_message properties: { v: 2, key: { starred._id: 1 }, name: "starred._id_1", ns: "rocketchat.rocketchat_message", sparse: 1 }
2021-05-18T08:57:47.998+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:47.998+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:50.217+0000 I STORAGE  [conn2] createCollection: rocketchat.omnichannel_auto_close_on_hold_scheduler with generated UUID: 26959395-e36d-499d-b8dc-5de298243455
2021-05-18T08:57:50.220+0000 I INDEX    [conn2] build index on: rocketchat.omnichannel_auto_close_on_hold_scheduler properties: { v: 2, key: { name: 1, nextRunAt: 1, priority: -1, lockedAt: 1, disabled: 1 }, name: "findAndLockNextJobIndex", ns: "rocketchat.omnichannel_auto_close_on_hold_scheduler" }
2021-05-18T08:57:50.220+0000 I INDEX    [conn2] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:50.220+0000 I INDEX    [conn2] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:50.222+0000 I STORAGE  [conn8] createCollection: rocketchat.omnichannel_scheduler with generated UUID: b68b4249-50bd-4343-9701-5e3f4f48d936
2021-05-18T08:57:50.223+0000 I INDEX    [conn8] build index on: rocketchat.omnichannel_scheduler properties: { v: 2, key: { name: 1, nextRunAt: 1, priority: -1, lockedAt: 1, disabled: 1 }, name: "findAndLockNextJobIndex", ns: "rocketchat.omnichannel_scheduler" }
2021-05-18T08:57:50.223+0000 I INDEX    [conn8] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:50.223+0000 I INDEX    [conn8] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:50.275+0000 I SHARDING [conn3] Marking collection rocketchat.ufsTokens as collection version: <unsharded>
2021-05-18T08:57:50.276+0000 I STORAGE  [conn6] createCollection: rocketchat.ufsTokens with generated UUID: 62113fc2-aaa4-4794-8ddc-7e5cdc7fab2e
2021-05-18T08:57:50.360+0000 I SHARDING [conn2] Marking collection rocketchat.rocketchat_avatars.files as collection version: <unsharded>
2021-05-18T08:57:50.364+0000 I STORAGE  [conn8] createCollection: rocketchat.rocketchat_avatars.files with generated UUID: e03141ed-bb44-4924-b371-c18d6f4fc725
2021-05-18T08:57:50.365+0000 I INDEX    [conn8] build index on: rocketchat.rocketchat_avatars.files properties: { v: 2, key: { filename: 1, uploadDate: 1 }, name: "filename_1_uploadDate_1", ns: "rocketchat.rocketchat_avatars.files", background: false }
2021-05-18T08:57:50.365+0000 I INDEX    [conn8] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:50.365+0000 I INDEX    [conn8] build index done.  scanned 0 total records. 0 secs
2021-05-18T08:57:50.366+0000 I SHARDING [conn3] Marking collection rocketchat.rocketchat_avatars.chunks as collection version: <unsharded>
2021-05-18T08:57:50.367+0000 I STORAGE  [conn6] createCollection: rocketchat.rocketchat_avatars.chunks with generated UUID: 9c24181e-48c7-4ec2-bc94-ce2c96378ad5
2021-05-18T08:57:50.368+0000 I INDEX    [conn6] build index on: rocketchat.rocketchat_avatars.chunks properties: { v: 2, unique: true, key: { files_id: 1, n: 1 }, name: "files_id_1_n_1", ns: "rocketchat.rocketchat_avatars.chunks", background: false }
2021-05-18T08:57:50.368+0000 I INDEX    [conn6] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T08:57:50.368+0000 I INDEX    [conn6] build index done.  scanned 0 total records. 0 secs
2021-05-18T09:02:23.071+0000 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
2021-05-18T09:02:23.071+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: f03ea0d5-ad62-4107-a9e1-b2d63ef03cbb
2021-05-18T09:02:23.073+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
2021-05-18T09:02:23.073+0000 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2021-05-18T09:02:23.073+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
```

**Comment by qiaofeng1227** [comment]
https://github.com/Websoft9/docker-rocketchat/blob/main/docker-compose.yml

use offical example compose is the same

**Comment by qiaofeng1227** [comment]
```
Edit the ROOT_URL value to be your FQDN.
Edit the ROCKETCHAT_URL to be your public IP address. Keep the port (3000) the same.
Edit ROCKETCHAT_USER, ROCKETCHAT_PASSWORD, and BOT_NAME.
If your Rocket.Chat docker instance is behind a proxy, set the additional env-variable "Accounts_UseDNSDomainCheck" to "false" (this only works, if these is a completely new deployment)
```
